# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overriden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
#
# More information on profiles: https://www.coolybot.tech/profiles/
# More information on configuration properties: https://www.coolybot.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

spring:
    application:
        name: coolybot-registry
    mvc:
        favicon:
            enabled: false
    security:
        user:
            name: admin
            password: admin
            roles: USER,ADMIN
    thymeleaf:
        mode: HTML

server:
    port: 8761

logging:
    file: target/coolybot-registry.log

ribbon:
    eureka:
        enabled: true

zuul:
    prefix: /services/ #slash before and after
    strip-prefix: true

management:
    endpoints:
        web:
            base-path: /management
            exposure:
                include: ["configprops", "env", "health", "info", "threaddump", "logfile", "clb-metrics"]
    endpoint:
        health:
            show-details: when_authorized
    health:
        mail:
            enabled: false # When using the MailService, configure an SMTP server and set this to true
    metrics:
        binders:
            jvm:
                enabled: true
            processor:
                enabled: true
            uptime:
                enabled: true
            logback:
                enabled: true
            files:
                enabled: true
            integration:
                enabled: true
        distribution:
            percentiles-histogram:
                all: true
            percentiles:
                all: 0, 0.5, 0.75, 0.95, 0.99, 1.0
        web:
            server:
                auto-time-requests: true

# ===================================================================
# Eureka server configuration (eureka.server.*)
#
# Full list of properties with default values at:
# https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-eureka-server/src/main/java/org/springframework/cloud/netflix/eureka/server/EurekaServerConfigBean.java
#
# Documentation at:
# https://github.com/Netflix/eureka/blob/master/eureka-core/src/main/java/com/netflix/eureka/EurekaServerConfig.java
# ===================================================================

eureka:
    instance:
        appname: coolybot-registry
        instanceId: coolybotRegistry:${spring.application.instance-id:${random.value}}
        prefer-ip-address: true
        lease-renewal-interval-in-seconds: 5
        lease-expiration-duration-in-seconds: 10
        status-page-url-path: ${management.endpoints.web.base-path}/info
        health-check-url-path: ${management.endpoints.web.base-path}/health
        metadata-map:
            zone: primary # This is needed for the load balancer
            profile: ${spring.profiles.active}
            version: ${info.project.version}
    client:
        enabled: true
        fetch-registry: false
        register-with-eureka: false
        instance-info-replication-interval-seconds: 10
        registry-fetch-interval-seconds: 10
        service-url:
            defaultZone: http://admin:${spring.security.user.password:admin}@localhost:${server.port}/eureka/
    server:
        # see discussion about enable-self-preservation:
        # https://github.com/coolybot/generator-coolybot/issues/3654
        enable-self-preservation: false
        peer-node-read-timeout-ms: 1000
    dashboard:
        path: /registry
    datacenter: Coolybot-DataCenter
    environment: Coolybot-Environment

coolybot:
    swagger:
        default-include-pattern: /(api|config)/.*
        title: Coolybot Registry API
        description: Coolybot Registry API documentation
        version: ${info.project.version}
